version: 2
jobs:
  build-go1.11.4:
    docker:
      - image: circleci/golang:1.13.6
    working_directory: /go/src/github.com/lesparzam/TestTLV
    steps:
      - checkout
      - run: go test -v -race ./...
      - run: go build -race src/main.go 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-go1.13.6